language: go
go: 
  - master

services:
  - docker

before_install:
  - mkdir -p /tmp/upload
  - cp dockerfile.sample Dockerfile
  - cp config.sample.yaml config.yaml
  - docker-compose up -d
  
script:
- go test ./... -v -cover
