source:
  type: sftp
  host: 0.0.0.0
  port: 22
  username: foo
  password: pass

target:
  type: http
  host: http://localhost:8080/upload-file
  header:
    - key: Authorization
      value: Basic 12345
  upload:
    - key: file
      value: file
    - key: statement_type
      value: withdrawal
  timeout: 5

cron:
  - name: get-sample-txt
    every: 5
    type: second
    specific_day: None
    task: 
      folder: /share/dumps
      file_prefix: \d*_\d*_\d*.\d*.\d*.csv$
      file_prefix_delimiter: .
      file_prefix_index: 1
 